build_settings:
    clone_depth: 1 # depth of 1 is a shallow clone, remove this line to clone entire repo
    ignore:
        - "vendor"
        - "Tests"
    \Rephlux\PHPCI\Plugin\ExternalEnvironment:
        master:
            env: "/var/www/phpci/.env/application.env"
    mysql:
        host: "localhost"
        user: "root"
        pass: ${db_pass}

setup:
    mysql:
        - "DROP DATABASE IF EXISTS test;"
        - "CREATE DATABASE test;"
        - "GRANT ALL PRIVILEGES ON test.* TO test@'localhost' IDENTIFIED BY 'test';"
    composer:
        action: "install"

#test:
#    php_unit:
#        directory:
#            - "Tests/"
#    php_mess_detector:
#        allow_failures: true
#    php_code_sniffer:
#        standard: "PSR2"
#    php_cpd:
#        allow_failures: true

complete:
    mysql:
        host: "localhost"
        user: "root"
        pass: ${db_pass}
        - "DROP DATABASE IF EXISTS test;"
