<?php

namespace TPS;
require_once dirname(__FILE__).DIRECTORY_SEPARATOR."../../TestsBase.php";
include dirname(__FILE__).DIRECTORY_SEPARATOR.'../../../public/lib/libs.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-28 at 22:37:01.
 */
class genreTest extends \TestsBase {

    /**
     * @var genre
     */
    protected $object;
    protected $singleResultTest = array(
            "Test"=>array(
                "governmentRequirements"=>array(
                    "type"=>"1",
                    "numeric"=>"3",
                    "percentage"=>"0.27"
                ),
                "playlistRequirements"=>array(
                    "type"=>"1",
                    "numeric"=>"12",
                    "percentage"=>"0.35"
                ),
                "femconRequirements"=>array(
                    "type"=>"1",
                    "numeric"=>"10",
                    "percentage"=>"0.46"
                ),
                "statistics"=>array(
                    "activePrograms"=>"1",
                    "totalPrograms"=>"1",
                    "percentPrograms"=>"1.0000"
                ),
                "UID"=>"18",
                "colorPrimary"=>"#4FC1E9",
                "station"=>"CKBD"
            )
        );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new genre("CKBD");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers TPS\genre::create
     * @todo   Implement testCreate().
     */
    public function testCreate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TPS\genre::change
     * @todo   Implement testChange().
     */
    public function testChange() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TPS\genre::all
     * @todo   Implement testAll().
     */
    public function testAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TPS\genre::get
     */
    public function testGet() {
        // Remove the following lines when you implement this test.
        $result = $this->object->get("TEST");
        $this->assertEquals($this->singleResultTest,$result);
    }

}
