<?php

namespace TPS;
include dirname(__FILE__).DIRECTORY_SEPARATOR.
                '../../../public/lib/tps.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-12 at 03:26:49.
 */
class TPSTest extends \PHPUnit_Extensions_Database_TestCase {

    /**
     * @var TPS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new \TPS\TPS(FALSE,FALSE);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        restore_include_path();
    }

    /**
     * @covers TPS\TPS::getStations
     * @todo   Implement testGetStations().
     */
    public function testGetStations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
    
    /**
     * @covers TPS\TPS::sanitizePagination
     */
    public function testSanitizePagination(){
        $page = 5;
        $max = 50;
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
        
    }
    
    /**
     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection
     */
    public function getConnection()
    {
        $pdo = new \PDO('sqlite::memory:');
        return $this->createDefaultDBConnection($pdo, ':memory:');
    }

    /**
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet()
    {
        return $this->createFlatXMLDataSet(dirname(__FILE__).'/_files/database-seed.xml');
    }

}
