<?php

namespace TPS;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-01-12 at 03:26:49.
 */
class TPSTest extends \PHPUnit_Extensions_Database_TestCase {

    /**
     * @var TPS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    /*protected function setUp() {
        $this->object = new TPS;
    }*/

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    /*protected function tearDown() {
        
    }*/

    /**
     * @covers TPS\TPS::getStations
     * @todo   Implement testGetStations().
     */
    public function testGetStations() {
        // Remove the following lines when you implement this test.
        /*$this->markTestIncomplete(
                'This test has not been implemented yet.'
        );*/
    }
    /**
     * @return PHPUnit_Extensions_Database_DB_IDatabaseConnection
     */
    public function getConnection()
    {
        $pdo = new \PDO('sqlite::memory:');
        return $this->createDefaultDBConnection($pdo, ':memory:');
    }

    /**
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet()
    {
        return $this->createFlatXMLDataSet(dirname(__FILE__).'/_files/guestbook-seed.xml');
    }

}
