CREATE TABLE `review` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `RefCode` BIGINT(20) UNSIGNED NOT NULL,
  `reviewer` VARCHAR(60) NOT NULL,
  `ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `approved` TINYINT(1) UNSIGNED NULL DEFAULT NULL,
  `femcon` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `hometown` VARCHAR(60) NULL,
  `subgenre` VARCHAR(60) NULL,
  `ip` INT(11) UNSIGNED NULL,
  `description` TEXT NOT NULL,
  `recommendations` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `refcode_idx` (`RefCode` ASC),
  CONSTRAINT `refcode`
    FOREIGN KEY (`RefCode`)
    REFERENCES `library` (`RefCode`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
